Run the search example from an Action
examples/README.md says that if I run `npm i` and then `NODE_PATH=../
node examples/search.js` from the root of the repo, the example will
run.

Of course when I run it, I get:

```
~/repos/puppeteer $ NODE_PATH=../ node examples/search.js
node:internal/modules/cjs/loader:571
      throw e;
      ^

Error: Cannot find module
'/Users/douglasnaphas/repos/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
    at resolveExports (node:internal/modules/cjs/loader:565:14)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename
(node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous>
(/Users/douglasnaphas/repos/puppeteer/examples/search.js:24:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  code: 'MODULE_NOT_FOUND',
  path:
'/Users/douglasnaphas/repos/puppeteer/node_modules/puppeteer/package.json'
}

Node.js v18.16.0
```

so I'm trying the command from an Action.