Tell Actions where to find the browser
My last build failed with:

Error: Could not find Chrome (ver. 118.0.5993.70). This can occur if
either
 1. you did not perform an installation before running the script (e.g.
    `npm install`) or
 2. your cache path is incorrectly configured (which is:
    /home/runner/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at
https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath
(/home/runner/work/puppeteer/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27)
    at ChromeLauncher.executablePath
(/home/runner/work/puppeteer/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:196:25)
    at ChromeLauncher.computeLaunchArguments
(/home/runner/work/puppeteer/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch
(/home/runner/work/puppeteer/puppeteer/packages/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
    at async
/home/runner/work/puppeteer/puppeteer/examples/search.js:27:19`

https://pptr.dev/troubleshooting#could-not-find-expected-browser-locally